# Local nginx server for testing purposes

FROM nginx:alpine
COPY default.conf /etc/nginx/conf.d/default.conf


## AWS READY NGINX CONFIGURATION

# FROM nginx:alpine

# # Remove default config
# RUN rm /etc/nginx/conf.d/default.conf

# # Copy custom nginx config
# COPY nginx.conf /etc/nginx/conf.d/default.conf